version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: databasename
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: spring-boot-app  # Use the name of the locally built Docker image
    container_name: spring_boot_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/databasename
      SPRING_DATASOURCE_USERNAME: usename
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres-data: